document.documentElement.classList.add('pages-js');
const gallery=document.querySelector('[data-gallery]');
if(gallery){
  const filters=[...document.querySelectorAll('.gallery-filter')],cards=[...document.querySelectorAll('.gallery-card')],count=document.querySelector('#gallery-count'),empty=document.querySelector('#gallery-empty'),categoryCta=document.querySelector('#category-cta-link'),categoryCopy=document.querySelector('#category-cta-copy'),dialog=document.querySelector('#gallery-lightbox'),dialogImage=document.querySelector('#lightbox-image'),dialogCaption=document.querySelector('#lightbox-caption'),dialogCount=document.querySelector('#lightbox-count'),closeButton=document.querySelector('#lightbox-close'),previousButton=document.querySelector('#lightbox-prev'),nextButton=document.querySelector('#lightbox-next');
  const validCategories=new Set(filters.map(button=>button.dataset.category));
  const ctaMap={all:['Explore Paint Events services','../services/','Choose the format that fits your group.'],corporate:['Request a Corporate Quote','../services/corporate-team-building/#inquiry','Planning a team experience? We’ll help shape the format.'],private:['Plan Your Celebration','../paint-events-booking-v2.html?type=private','Start with a preferred date and celebration details.'],kids:['Explore Kids and School Events','../services/#kids-schools','See formats designed for young artists and schools.'],community:['Explore Community Programs','../services/#community-programs','Plan a welcoming creative program for your community.'],festivals:['Discuss a Large-Group Activation','../services/#festivals-large-groups','Tell us about your audience, venue, and event scale.'],pet:['Plan a Paint Your Pet Event','../services/#paint-your-pet','Explore the Paint Your Pet experience and request details.'],picnic:['Plan an Outdoor Experience','../services/#picnic-painting','Bring guided creativity to a picnic or outdoor gathering.'],crafts:['Plan a Custom Craft Session','../services/#crafts-mixed-media','Share your group and creative goals for a tailored session.'],collaborative:['Explore Collaborative Art','../services/#collaborative-art','Create one shared piece with your team or community.']};
  let visibleCards=[],activeIndex=0,returnFocus=null,pointerStartX=null;
  function applyFilter(category,updateUrl=true){const safe=validCategories.has(category)?category:'all';filters.forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.category===safe)));cards.forEach(card=>{const tags=(card.dataset.tags||'').split(' ');card.hidden=safe!=='all'&&!tags.includes(safe)});visibleCards=cards.filter(card=>!card.hidden);if(count)count.textContent=`${visibleCards.length} approved ${visibleCards.length===1?'image':'images'}`;empty?.classList.toggle('is-visible',visibleCards.length===0);const[label,href,copy]=ctaMap[safe]||ctaMap.all;if(categoryCta){categoryCta.textContent=label;categoryCta.href=href}if(categoryCopy)categoryCopy.textContent=copy;if(updateUrl){const url=new URL(location.href);safe==='all'?url.searchParams.delete('category'):url.searchParams.set('category',safe);history.replaceState(null,'',`${url.pathname}${url.search}${url.hash}`)}}
  function showLightbox(index){if(!visibleCards.length||!dialogImage)return;activeIndex=(index+visibleCards.length)%visibleCards.length;const button=visibleCards[activeIndex].querySelector('.gallery-open');dialogImage.src=button.dataset.full;dialogImage.alt=button.dataset.alt;if(dialogCaption)dialogCaption.textContent=button.dataset.caption;if(dialogCount)dialogCount.textContent=`${activeIndex+1} of ${visibleCards.length}`}
  filters.forEach(button=>button.addEventListener('click',()=>applyFilter(button.dataset.category)));
  cards.forEach(card=>card.querySelector('.gallery-open')?.addEventListener('click',event=>{returnFocus=event.currentTarget;visibleCards=cards.filter(item=>!item.hidden);showLightbox(visibleCards.indexOf(card));dialog?.showModal();closeButton?.focus()}));
  closeButton?.addEventListener('click',()=>dialog?.close());previousButton?.addEventListener('click',()=>showLightbox(activeIndex-1));nextButton?.addEventListener('click',()=>showLightbox(activeIndex+1));dialog?.addEventListener('close',()=>{dialogImage?.removeAttribute('src');returnFocus?.focus()});dialog?.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
  dialog?.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();dialog.close()}if(event.key==='ArrowLeft'){event.preventDefault();showLightbox(activeIndex-1)}if(event.key==='ArrowRight'){event.preventDefault();showLightbox(activeIndex+1)}if(event.key==='Tab'){const focusable=[closeButton,previousButton,nextButton].filter(Boolean),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
  dialog?.addEventListener('pointerdown',event=>{pointerStartX=event.clientX});dialog?.addEventListener('pointerup',event=>{if(pointerStartX===null)return;const distance=event.clientX-pointerStartX;pointerStartX=null;if(Math.abs(distance)>60)showLightbox(activeIndex+(distance<0?1:-1))});
  applyFilter(new URLSearchParams(location.search).get('category')||'all',false);
}

const corporateForm=document.querySelector('#corporate-inquiry-form');
if(corporateForm){
  const status=document.querySelector('#corporate-form-status'),submitButton=corporateForm.querySelector('button[type=submit]'),draftKey='paintEventsCorporateDraft';let requestStarted=false;
  function setError(field,message){const error=document.querySelector(`#${field.id}-error`);field.setAttribute('aria-invalid',String(Boolean(message)));if(error)error.textContent=message}
  function validateField(field){const value=field.value.trim();let message='';if(field.required&&!value)message='This field is required.';else if(field.type==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))message='Enter a valid email address.';else if(field.id==='corporate-participants'&&value&&(Number(value)<4||Number(value)>1000))message='Enter an estimated group size from 4 to 1,000.';setError(field,message);return!message}
  function saveDraft(){try{sessionStorage.setItem(draftKey,JSON.stringify(Object.fromEntries(new FormData(corporateForm).entries())))}catch(error){}}
  try{const saved=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(saved)Object.entries(saved).forEach(([name,value])=>{const field=corporateForm.elements.namedItem(name);if(field)field.value=value})}catch(error){}
  corporateForm.addEventListener('input',event=>{if(event.target.matches('input,select,textarea')){validateField(event.target);saveDraft()}});
  corporateForm.addEventListener('submit',event=>{event.preventDefault();if(requestStarted)return;const fields=[...corporateForm.querySelectorAll('input,select,textarea')],valid=fields.map(validateField).every(Boolean),firstInvalid=corporateForm.querySelector('[aria-invalid=true]');if(!valid||firstInvalid){if(status)status.textContent='Review the highlighted fields before continuing.';firstInvalid?.focus();return}requestStarted=true;submitButton.disabled=true;submitButton.textContent='Preparing email draft…';const v=Object.fromEntries(new FormData(corporateForm).entries()),lines=['Corporate Paint Events inquiry','',`Name: ${v.name}`,`Work email: ${v.email}`,`Company: ${v.company}`,`Role / department: ${v.role}`,`Phone: ${v.phone}`,`Preferred date: ${v.preferredDate}`,`Alternative date: ${v.alternativeDate||'Not provided'}`,`Location / ZIP: ${v.location}`,`Estimated participants: ${v.participants}`,`Event type: ${v.eventType}`,`Preferred activity: ${v.activity}`,`Setting: ${v.setting}`,`Duration: ${v.duration}`,`Budget range: ${v.budget||'Not provided'}`,`Event objective: ${v.objective}`,`Accessibility needs: ${v.accessibility||'None provided'}`,`Additional notes: ${v.notes||'None provided'}`,'','This is an event request for review, not a confirmed booking.'];if(status)status.textContent='Your email app is opening with the inquiry details. Review the message and press Send. Paint Events will reply with availability and next steps.';submitButton.textContent='Email draft opened';location.href=`mailto:info@paint.events?subject=${encodeURIComponent(`Corporate event inquiry — ${v.company}`)}&body=${encodeURIComponent(lines.join('\n'))}`});
}
